apiVersion: v1
kind: Service
metadata:
  name: resilient-inference-server-spot
  labels:
    app: resilient-inference-server
    node-pool: spot
spec:
  type: ClusterIP
  selector:
    app: resilient-inference-server
    node-pool: spot
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
